### ISSUE TITLE
How to run it in dev mode?

### ISSUE THREAD

**Issue by mateuszmazurek** [ospfranco/sol#102]
I want to play around with code and maybe create some features but I need to know how to run this app in development mode first. There's no such info in README and I didn't find any related issue.

Btw great app, I hope it will replace Raycast soon on my Mac :) Raycast is almost perfect but not open source and I can't tweak some things which frustrate me. I totally understand your motivations to start this project.

**Comment by ospfranco** [comment]
setup is a bit complex, I think there is an old issue somewhere that contains some instructions.

Some rough guideline:

- set up node 16 with yarn
- `yarn install`
- `npx pod-install macos`
- yarn macos

You might get some certificate issue because right now the signing config is set to my own apple account but you can open the .xcworkspace project on xcode and remove it and try to build it from there

**Comment by mateuszmazurek** [comment]
thanks, will give it a try

**Comment by ospfranco** [comment]
Here are some more detailed instruction although they might still be incomplete:

- Install Xcode
- Set up node 16 with yarn
- Install ruby 2.7.6 ➡️ `sudo gem install bundler` ➡️ `bundle install` on the root of project
- `yarn`
- `npx pod-install`
- `yarn macos`

As stated you might have an issue trying to run the app with my hardcoded team id, on which case you want to go into xcode and remove the assigned team from `Signing` config. From the top of my head that is all. Let me know if you face any other issue.
