### ISSUE TITLE
Forward media keys to media player setting won't persist over app restart

### ISSUE THREAD

**Issue by thebiblelover7** [ospfranco/sol#126]
When I disable in "Sol Settings" the Forward media keys to media player, it only works for the time that Sol is open. Once I quit the app, restart my computer, or log out, I need to change this setting again.

Also, as a side note, I don't see the use of this "feature", at least Sol has never "forwarded" the keys to the current media player that I've noticed....

**Comment by ospfranco** [comment]
This feature is meant to prevent the case where you have music playing in apple music/spotify and video is playing in your web browser (YouTube, Vimeo, w/e) and you press play/pause on the fn keys row and instead of pausing the music it pauses the video, it should instead pause the music. It does not work with other media players.

As for it working, please test the scenario I just described. Accessibility should be enabled for this feature to work. I have noticed on the latest macOS version the accessibility prompt sometimes doesn't work, so you might need to enable it manually.

**Comment by thebiblelover7** [comment]
Makes sense.... I hope it can be expanded to other media players later :).... 


> As for it working, please test the scenario I just described. Accessibility should be enabled for this feature to work. I have noticed on the latest macOS version the accessibility prompt sometimes doesn't work, so you might need to enable it manually.

Accessibility access is actually granted for Sol, but I have the same issue, and I don't think it's relevant.
I don't think the issue is the actual forwarding, Sol is *not saving the state* of the "Forward media keys to media player" setting...

**Comment by ospfranco** [comment]
Ah! That's a different thing, you might be one of the affected users by some weird bug where all of the settings are not saved. Which version are you using?

**Comment by thebiblelover7** [comment]
I am using v2.1.55

**Comment by thebiblelover7** [comment]
Apologies if I didn't make it clear....

**Comment by ospfranco** [comment]
Found the issue, will be fixed on next release

**Comment by thebiblelover7** [comment]
Can confirm, it works now! Thanks @ospfranco !
