### ISSUE TITLE
Request: search system preferences

### ISSUE THREAD

**Issue by mfbx9da4** [ospfranco/sol#34]
It would be cool to search the system preferences and deep link into the setting

**Comment by ospfranco** [comment]
So far I've only hardcoded the display settings, maybe there is a way to get the list of items programmatically in Swift. If you can figure it out feel free to tackle it... otherwise I might try to take a look much later.

**Comment by mfbx9da4** [comment]
I've found this list but I don't see how to import the `SystemPreferences` Object? Any ideas. Otherwise I'm happy to hardcode the list

**Comment by mfbx9da4** [comment]
Threw this together https://github.com/ospfranco/sol/pull/36

It does unfortunately contain some unrelated stying fixees though

**Comment by ospfranco** [comment]
thanks for the PR! It's merged and I will create a release soon. 

Just as a friendly request, I put a couple of extra minutes to put a name field on most items, I try to keep the app polished enough so that there are no glaring flaws, next time would be great if you could also tackle that as well :)

**Comment by mfbx9da4** [comment]
Yeah absolutely did it very quickly and was excited to see it working but definitely could have spent more time curating the individual items. I think it would be nicer if each preference had the system preference icon, will add!
