### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by huabin** [ospfranco/sol#79]
Hello,

I'd like to ask what the plugin system will look like? Is it possible to have something like Raycast scripts-command?

Thank you.

**Comment by huabin** [comment]
BTW, I thought the scripts command is much simpler and easier to extend.

**Comment by ospfranco** [comment]
You can already create applescripts or url shortcuts, just search for "Create Shortcut". As for the plugin system, yeah, it should be something akin to Raycast plugins, but I don't know when I will have time to tackle something like that.

**Comment by huabin** [comment]
I see, I will try, thank you.

BTW, my suggestion is don't make the plugin system look like what Raycast
extension is now, it should look like what it was originally. Raycast
extension is so heavy now. I used to be interested in contributing scripts
to Raycast and have written a few, but I'm not interested in writing
extensions for it at all.

SOL = Core + scripts-commands (hosted on GitHub, everyone can contribute to
it.)

That will be so perfect. Just my personal opinion. Hope will help.

**Comment by ospfranco** [comment]
no sorry, scripts are fine for one time use cases, but for stuff like forms and meaningful interactions with other apps and web services one needs a real plugin system where one can build UI elements. Sure scripts have a place for certain stuff, but they are also kinda awkward to write and maintain. Going to close this for now, since it is not an issue but more of a discussion.

**Comment by huabin** [comment]
I see, I will fork one and build a sol without extensions :)

**Comment by ospfranco** [comment]
Don't think you realize the amount of work it takes to keep up with upstream changes and keep releasing the app all the time, but you are free to do as you please, Sol is MIT.
